export enum ActionType {
  CHANGE_FIRST_NAME = 'CHANGE_FIRST_NAME',
  CHANGE_LAST_NAME = 'CHANGE_LAST_NAME',
  CHANGE_USERNAME = 'CHANGE_USERNAME',
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CHANGE_REPEAT_PASSWORD = 'CHANGE_REPEAT_PASSWORD',
}
